# Generated by Django 5.1.4 on 2025-02-06 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_apellido_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='Apellidoo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(default='Ciudadd', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_postal',
            field=models.CharField(default='12345', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='domicilio',
            field=models.CharField(default='la casaaa', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_de_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='nombreee', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.CharField(default='paisss', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(default='provinciaa', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=213122183, max_length=15),
            preserve_default=False,
        ),
    ]
