# Generated by Django 5.1.4 on 2025-01-07 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDePieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('autora', models.CharField(choices=[('AGV', 'Ariadna Gorostegui Valenti'), ('VC', 'Veronica Cepeda')], max_length=3)),
                ('imagen', models.ImageField(blank=True, upload_to='piezas')),
                ('fecha_de_publicacion', models.DateTimeField(verbose_name='Fecha de publicación')),
                ('cantidad', models.IntegerField(default=1)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.tipodepieza')),
            ],
        ),
    ]
