# Generated by Django 5.1.4 on 2025-01-03 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('author', models.CharField(choices=[('AGV', 'Ariadna Gorostegui Valenti'), ('VC', 'Veronica Cepeda')], max_length=3)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.typeofproduct')),
            ],
        ),
    ]
