# Generated by Django 5.1.4 on 2025-01-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='descripcion',
            field=models.CharField(default='Descripcion', max_length=300),
            preserve_default=False,
        ),
    ]
