# Generated by Django 5.1.4 on 2025-01-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofproduct',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='typeofproduct',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
