# Generated by Django 5.1.4 on 2025-01-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_pieza_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pieza',
            old_name='cantidad',
            new_name='stock',
        ),
    ]
