# Generated by Django 5.1.4 on 2025-01-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_typeofproduct_description_alter_typeofproduct_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='piezas'),
        ),
    ]
