# Generated by Django 5.1.6 on 2025-02-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_pieza_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='imagen',
            field=models.ImageField(default='piezas/florero-lineas_vWeMy9V.jpg', upload_to='piezas'),
            preserve_default=False,
        ),
    ]
